# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e860c614fbdd427a8041f4a1c60c2eb95974bee0fd5b8dae05f31a87430e6b7ef2741f4fcf85ae4881d52878feb390cecebcec37e820eb7e922ba755f4f7144f

test:
  secret_key_base: 60b3ca0a7e74283ae687b7db26ecc42b312ba4596762589f42a70c053df9c8d5fd2c7934af4f231a006a98d816b3e4ff211b202af932d20b11e67d9cd3584637

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
